name: Ruff Lint Check

on:
  push:
    branches:
      - main
      - '**/*'
  pull_request:
    branches:
      - main

jobs:
  ruff-lint:
    name: Run Ruff Lint Check
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12  # or your preferred version

    # Step 3: Install Ruff
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.dev.txt

    # Step 4: Run Ruff
    - name: Run Ruff Lint
      id: ruff-linter
      run: |
        ruff check --output-format=github .
